[project]
name = "diffusion-curvature"
version = "0.1.0"
description = "Fast pointwise Graph Curvature"
authors = ["Kincaid MacDonald <dev@riddle.press>"]
channels = ["conda-forge", "fastai", "pytorch"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.11.*"
numpy = "1.26.2.*"
matplotlib = "3.8.2.*"
notebook = "7.0.6.*"
scipy = "1.11.4.*"
ipykernel = "6.26.0.*"
jupyter = "1.0.0.*"
nbformat = "5.9.2.*"
graphtools = "1.5.3.*"
jax = "0.4.21.*"
sympy = "1.12.*"
rich = "13.7.0.*"
typer = "0.9.0.*"
pygsp = "0.5.1.*"
tqdm = "4.66.1.*"
plotly = "5.18.0.*"
fastcore = "1.5.29.*"
nbdev = "2.2.10.*"
pytorch = "2.0.0.*"
lightning = "2.1.2.*"
pandas = "2.1.3.*"
seaborn = "0.13.0.*"
h5py = "3.10.0.*"

[pypi-dependencies]
scikit-dimension = "==0.3.*"
flax = ">=0.7.5"
magic-impute = "==3.0.*"

